name: Update README web pages

# Grant write permission to contents so the GITHUB_TOKEN can push commits
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make script executable
        run: chmod +x ./scripts/update_readme.sh

      - name: Run update script
        env:
          BASE_URL: https://fernando-tupana.github.io/projects_map
        run: |
          ./scripts/update_readme.sh
